/*
 * Copyright 2026 Marco Ferretti
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.datagenerator.inspector.ddl;

import static com.datagenerator.inspector.InspectionTestSupport.datatypesOf;
import static org.assertj.core.api.Assertions.*;

import com.datagenerator.inspector.Inspection;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * #215: a {@code GENERATED ALWAYS AS IDENTITY} primary key is DB-assigned — the database rejects a
 * client-supplied value — so the inspector must NOT emit a {@code serial} (or any) value for it.
 *
 * <p>Behaviour contract:
 *
 * <ul>
 *   <li>Unreferenced single-column {@code GENERATED ALWAYS} identity PK → the column is
 *       <b>omitted</b> from the emitted structure (the DB assigns it), with a warning.
 *   <li>If a child FK references it, omitting would dangle that ref (cross-table ordered generation
 *       is #400), so the column is <b>kept</b> as {@code serial} with a warning pointing at #400.
 *   <li>{@code GENERATED BY DEFAULT AS IDENTITY}, plain {@code SERIAL}, and non-identity PKs accept
 *       a client value → unchanged ({@code serial}). (regression guards)
 *   <li>A {@code GENERATED ALWAYS} column inside a composite PK is <b>retained</b> (only
 *       single-column identity PKs are omitted). (regression guard)
 * </ul>
 */
class DdlInspectorGeneratedIdentityTest {

  // --- new behaviour (expected RED until #215 is implemented) ---

  @Test
  void shouldOmitUnreferencedGeneratedAlwaysIdentityPkAndWarn(@TempDir Path dir)
      throws IOException {
    Inspection in =
        inspect(
            dir,
            "CREATE TABLE account (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,"
                + " name VARCHAR(100) NOT NULL);");

    // The id column must not be emitted at all — the DB assigns it.
    assertThat(datatypesOf(in, "account")).doesNotContainKey("id").containsKey("name");
    assertThat(in.warnings())
        .anyMatch(
            w ->
                w.contains("account.id")
                    && w.contains("GENERATED ALWAYS")
                    && w.toLowerCase(Locale.ROOT).contains("omit"));
  }

  @Test
  void shouldKeepGeneratedAlwaysIdentityPkAsSerialWhenReferencedAndWarn(@TempDir Path dir)
      throws IOException {
    Inspection in =
        inspect(
            dir,
            """
            CREATE TABLE account (
              id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
              name VARCHAR(100) NOT NULL
            );
            CREATE TABLE txn (
              id BIGINT PRIMARY KEY,
              account_id BIGINT REFERENCES account(id),
              amount INT
            );
            """);

    // Omitting would leave txn.account_id referencing a missing field, so the PK is kept...
    assertThat(datatypesOf(in, "account")).containsEntry("id", "serial");
    assertThat(datatypesOf(in, "txn")).containsEntry("account_id", "ref[account.id, 1..count]");
    // ...with a warning that names the referencing situation and points at the follow-up (#400).
    assertThat(in.warnings())
        .anyMatch(
            w ->
                w.contains("account.id")
                    && w.toLowerCase(Locale.ROOT).contains("referenc")
                    && w.contains("#400"));
  }

  @Test
  void shouldDetectGeneratedAlwaysCaseInsensitively(@TempDir Path dir) throws IOException {
    Inspection in =
        inspect(
            dir,
            "CREATE TABLE account (id BIGINT generated   always as identity PRIMARY KEY,"
                + " name VARCHAR(100) NOT NULL);");

    assertThat(datatypesOf(in, "account")).doesNotContainKey("id").containsKey("name");
  }

  @Test
  void shouldOmitGeneratedAlwaysIdentityPkInNestedMode(@TempDir Path dir) throws IOException {
    Inspection in =
        new DdlInspector()
            .inspect(
                write(
                    dir,
                    "CREATE TABLE account (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,"
                        + " name VARCHAR(100) NOT NULL);"),
                NestingOptions.parse("auto", null));

    assertThat(datatypesOf(in, "account")).doesNotContainKey("id").containsKey("name");
  }

  // --- regression guards (expected GREEN before and after #215) ---

  @Test
  void shouldKeepGeneratedByDefaultIdentityAsSerial(@TempDir Path dir) throws IOException {
    Inspection in =
        inspect(
            dir,
            "CREATE TABLE ledger (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + " note VARCHAR(50));");

    // BY DEFAULT accepts a client-supplied value — must stay serial, never omitted.
    assertThat(datatypesOf(in, "ledger")).containsEntry("id", "serial");
  }

  @Test
  void shouldKeepSerialPrimaryKeyAsSerial(@TempDir Path dir) throws IOException {
    Inspection in = inspect(dir, "CREATE TABLE s (id SERIAL PRIMARY KEY, n INT);");

    assertThat(datatypesOf(in, "s")).containsEntry("id", "serial");
  }

  @Test
  void shouldRetainGeneratedAlwaysColumnInCompositePrimaryKey(@TempDir Path dir)
      throws IOException {
    Inspection in =
        inspect(
            dir,
            """
            CREATE TABLE t (
              id BIGINT GENERATED ALWAYS AS IDENTITY,
              tenant INT,
              PRIMARY KEY (id, tenant)
            );
            """);

    // Only single-column identity PKs are omitted; a composite member is retained.
    assertThat(datatypesOf(in, "t")).containsKey("id").containsKey("tenant");
  }

  private Path write(Path dir, String ddl) throws IOException {
    Path sql = dir.resolve("schema.sql");
    Files.writeString(sql, ddl);
    return sql;
  }

  private Inspection inspect(Path dir, String ddl) throws IOException {
    return new DdlInspector().inspect(write(dir, ddl));
  }
}
