name: lib_magazine
data:
  id:
    datatype: int[1..80]
  title:
    datatype: lorem_sentence
  issn:
    datatype: char[8..8]
  frequency:
    datatype: enum[WEEKLY,MONTHLY,QUARTERLY,ANNUAL]
  cover_price:
    datatype: decimal[1.99..29.99]
  category:
    datatype: enum[SCIENCE,TECHNOLOGY,ARTS,SPORTS,NEWS,CULTURE,HEALTH]
  publisher_id:
    datatype: ref[lib_publication.id, 1..20]
  lib_magazine_sales:
    datatype: array[object[lib_magazine_sale], 0..30]
