name: lib_book
data:
  id:
    datatype: int[1..500]
  title:
    datatype: lorem_sentence
  isbn:
    datatype: isbn
  genre:
    datatype: enum[FICTION,NON_FICTION,SCIENCE,HISTORY,BIOGRAPHY,FANTASY,MYSTERY,ROMANCE]
  pages:
    datatype: int[50..1200]
  language:
    datatype: enum[EN,IT,FR,DE,ES]
  price:
    datatype: decimal[5.00..99.99]
  published_date:
    datatype: date[1900-01-01..2025-12-31]
  author_id:
    datatype: ref[parent.id]
  publisher_id:
    datatype: ref[lib_publication.id, 1..20]
  lib_book_sales:
    datatype: array[object[lib_book_sale], 0..10]
  lib_supplies:
    datatype: array[object[lib_supply], 0..3]
