/*
 * Copyright 2026 Marco Ferretti
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.datagenerator.generators.semantic;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import net.datafaker.Faker;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

class FakerCacheTest {

  @AfterEach
  void cleanup() {
    FakerCache.clear();
  }

  @Test
  void shouldReturnSameFakerInstanceForSameLocaleInSameThread() {
    Random random = new Random(42);
    Locale locale = Locale.ITALY;

    Faker faker1 = FakerCache.getOrCreate(locale, random);
    Faker faker2 = FakerCache.getOrCreate(locale, random);

    assertThat(faker1).isSameAs(faker2);
  }

  @Test
  void shouldReturnDifferentFakersForDifferentLocalesInSameThread() {
    Random random = new Random(42);

    Faker italianFaker = FakerCache.getOrCreate(Locale.ITALY, random);
    Faker frenchFaker = FakerCache.getOrCreate(Locale.FRANCE, random);

    assertThat(italianFaker).isNotSameAs(frenchFaker);
    assertThat(FakerCache.getCacheSize()).isEqualTo(2);
  }

  @Test
  void shouldReturnDifferentFakersForDifferentThreads() throws Exception {
    Random random = new Random(42);
    Locale locale = Locale.ITALY;
    Set<Faker> fakers = ConcurrentHashMap.newKeySet();

    ExecutorService executor = Executors.newFixedThreadPool(3);
    CountDownLatch latch = new CountDownLatch(3);

    for (int i = 0; i < 3; i++) {
      executor.submit(
          () -> {
            Faker faker = FakerCache.getOrCreate(locale, random);
            fakers.add(faker);
            latch.countDown();
          });
    }

    latch.await(5, TimeUnit.SECONDS);
    executor.shutdown();
    executor.awaitTermination(5, TimeUnit.SECONDS);

    // Each thread should get its own Faker instance
    assertThat(fakers).hasSize(3);
  }

  @Test
  void shouldClearCacheForCurrentThread() {
    Random random = new Random(42);
    Faker faker1 = FakerCache.getOrCreate(Locale.ITALY, random);
    assertThat(FakerCache.getCacheSize()).isEqualTo(1);

    FakerCache.clear();
    assertThat(FakerCache.getCacheSize()).isEqualTo(0);

    // After clear, should create new instance (even with same Random)
    Random random2 = new Random(42); // Use new Random with same seed
    Faker faker2 = FakerCache.getOrCreate(Locale.ITALY, random2);
    assertThat(FakerCache.getCacheSize()).isEqualTo(1);
    assertThat(faker2).isNotSameAs(faker1);
  }

  @Test
  void shouldGenerateDeterministicDataWithCachedFaker() {
    Random random = new Random(12345);
    Faker faker = FakerCache.getOrCreate(Locale.ITALY, random);

    String name1 = faker.name().fullName();
    String name2 = faker.name().fullName();

    // Different values (Random state progresses)
    assertThat(name1).isNotEqualTo(name2);

    // But reusing same faker should be deterministic
    Random random2 = new Random(12345);
    FakerCache.clear();
    Faker faker2 = FakerCache.getOrCreate(Locale.ITALY, random2);
    String name3 = faker2.name().fullName();

    assertThat(name3).isEqualTo(name1); // Same seed = same first value
  }

  @Test
  void shouldHandleMultipleLocalesInSameThread() {
    Random random = new Random(42);

    Faker enFaker = FakerCache.getOrCreate(Locale.US, random);
    Faker itFaker = FakerCache.getOrCreate(Locale.ITALY, random);
    Faker frFaker = FakerCache.getOrCreate(Locale.FRANCE, random);

    assertThat(FakerCache.getCacheSize()).isEqualTo(3);

    // Verify reuse
    Faker enFaker2 = FakerCache.getOrCreate(Locale.US, random);
    assertThat(enFaker2).isSameAs(enFaker);
    assertThat(FakerCache.getCacheSize()).isEqualTo(3); // Still 3, not 4
  }

  @Test
  void shouldMaintainDeterminismAcrossMultipleThreadsWithDifferentSeeds() throws Exception {
    Locale locale = Locale.US;
    int numThreads = 3;
    int valuesPerThread = 5;

    // Map to store values generated by each thread
    Map<Integer, List<String>> resultsByThread = new ConcurrentHashMap<>();

    ExecutorService executor = Executors.newFixedThreadPool(numThreads);
    CountDownLatch latch = new CountDownLatch(numThreads);

    // Each thread uses different seed (simulating RandomProvider behavior)
    for (int threadId = 0; threadId < numThreads; threadId++) {
      int finalThreadId = threadId;
      executor.submit(
          () -> {
            try {
              // Each thread gets its own Random with deterministic seed
              // (this simulates RandomProvider.getRandom() behavior)
              Random random = new Random(1000L + finalThreadId);

              List<String> values = new ArrayList<>();
              Faker faker = FakerCache.getOrCreate(locale, random);

              // Generate multiple values
              for (int i = 0; i < valuesPerThread; i++) {
                values.add(faker.name().fullName());
              }

              resultsByThread.put(finalThreadId, values);
              latch.countDown();
            } finally {
              FakerCache.clear();
            }
          });
    }

    latch.await(10, TimeUnit.SECONDS);
    executor.shutdown();
    executor.awaitTermination(10, TimeUnit.SECONDS);

    // Verify: Each thread generated different values (different seeds)
    assertThat(resultsByThread).hasSize(numThreads);
    List<String> thread0Values = resultsByThread.get(0);
    List<String> thread1Values = resultsByThread.get(1);
    List<String> thread2Values = resultsByThread.get(2);

    // Different threads with different seeds should generate different data
    assertThat(thread0Values).isNotEqualTo(thread1Values);
    assertThat(thread1Values).isNotEqualTo(thread2Values);

    // Now verify reproducibility: Run again with same seeds
    resultsByThread.clear();
    CountDownLatch latch2 = new CountDownLatch(numThreads);
    ExecutorService executor2 = Executors.newFixedThreadPool(numThreads);

    for (int threadId = 0; threadId < numThreads; threadId++) {
      int finalThreadId = threadId;
      executor2.submit(
          () -> {
            try {
              // SAME seed as first run
              Random random = new Random(1000L + finalThreadId);

              List<String> values = new ArrayList<>();
              Faker faker = FakerCache.getOrCreate(locale, random);

              for (int i = 0; i < valuesPerThread; i++) {
                values.add(faker.name().fullName());
              }

              resultsByThread.put(finalThreadId, values);
              latch2.countDown();
            } finally {
              FakerCache.clear();
            }
          });
    }

    latch2.await(10, TimeUnit.SECONDS);
    executor2.shutdown();
    executor2.awaitTermination(10, TimeUnit.SECONDS);

    // CRITICAL: Same seeds should produce IDENTICAL data (reproducibility)
    assertThat(resultsByThread.get(0)).isEqualTo(thread0Values);
    assertThat(resultsByThread.get(1)).isEqualTo(thread1Values);
    assertThat(resultsByThread.get(2)).isEqualTo(thread2Values);
  }
}
